language: node_js
node_js:
  - '12'
script:
  - npm run build
deploy:
  local_dir: dist
  email: myles.borins@gmail.com
  name: Myles Borins
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
